export const DesignationOptions = [
  { value: "1", label: "Select Designation" },
  { value: "25", label: "HR Executive" },
  { value: "63", label: "Software Engineer" },
  { value: "76", label: "Sr. Software Engineer" },
  { value: "32", label: "Jr. Web Designer" },
  { value: "79", label: "Sr. Web Designer" },
  { value: "86", label: "Team Leader" },
  { value: "91", label: "Trainee Software Engineer" },

  // { value: "2", label: "Accounting Assistant" },
  // { value: "3", label: "Accounting Head" },
  // { value: "4", label: "Admin" },
  // { value: "5", label: "Assistant" },
  // { value: "6", label: "Assistant HR Executive" },
  // { value: "7", label: "Assistant Network Engineer" },
  // { value: "8", label: "Assistant Project Manager" },
  // { value: "9", label: "Associate Team Leader" },
  // { value: "10", label: "Associate Team Leader - Marketing" },
  // { value: "11", label: "Back Office Supervisor" },
  // { value: "12", label: "Business Development Executive" },
  // { value: "13", label: "Business Development Executive" },
  // { value: "14", label: "Business Development Manager" },
  // { value: "15", label: "Campaign Manager" },
  // { value: "16", label: "Chief Executive Officer" },
  // { value: "17", label: "Chief Technology Officer" },
  // { value: "18", label: "Composition Analyst" },
  // { value: "19", label: "Content Leader" },
  // { value: "20", label: "Content Project Manager" },
  // { value: "21", label: "Content Writer" },
  // { value: "22", label: "Digital Marketing Analyst" },
  // { value: "23", label: "English Trainer" },
  // { value: "24", label: "Graphic Analyst" },
  // { value: "26", label: "HR Manager" },
  // { value: "27", label: "Jr. Business Development Associate" },
  // { value: "28", label: "Jr. Business Development Executive" },
  // { value: "29", label: "Jr. Marketing Executive" },
  // { value: "30", label: "Jr. Promotion Analyst" },
  // { value: "31", label: "Jr. Web Analyst" },
  // { value: "33", label: "Jr.SEO Professional" },
  // { value: "34", label: "Lead Administrator Networking" },
  // { value: "35", label: "Lead Website Administrator" },
  // { value: "36", label: "Link Building Specialist" },
  // { value: "37", label: "Marketing Executive" },
  // { value: "38", label: "Media Analyst" },
  // { value: "39", label: "Mobile App. Designer" },
  // { value: "40", label: "Network Administrator" },
  // { value: "41", label: "Online Administrator" },
  // { value: "42", label: "Online Data Entry Operator" },
  // { value: "43", label: "Online Marketing Executive" },
  // { value: "44", label: "Peon" },
  // { value: "45", label: "President – HR" },
  // { value: "46", label: "Project Manager" },
  // { value: "47", label: "QA Engineer" },
  // { value: "48", label: "Requirement Analyst" },
  // { value: "49", label: "Sales Executive" },
  // { value: "60", label: "SEO Assistant Team Leader" },
  // { value: "61", label: "SEO Professional" },
  // { value: "62", label: "SEO Team Leader" },
  // { value: "64", label: "Sr. Assistant Team Leader" },
  // { value: "65", label: "Sr. Business Development Executive" },
  // { value: "66", label: "Sr. Composition Analyst" },
  // { value: "67", label: "Sr. Content Writer" },
  // { value: "68", label: "Sr. HR Executive" },
  // { value: "69", label: "Sr. HR Manager" },
  // { value: "70", label: "Sr. Marketing Business Analyst" },
  // { value: "71", label: "Sr. Marketing Executive" },
  // { value: "72", label: "Sr. Mobile App Designer" },
  // { value: "73", label: "Sr. Network Administrator" },
  // { value: "74", label: "Sr. QA Engineer" },
  // { value: "75", label: "Sr. Sales Executive" },
  // { value: "77", label: "Sr. Team Leader" },
  // { value: "78", label: "Sr. Web Analyst" },
  // { value: "80", label: "Sr. Website Administrator" },
  // { value: "81", label: "Sr.Business Development Manager" },
  // { value: "82", label: "Sr.Campaign Manager" },
  // { value: "83", label: "Sr.Graphic Analyst" },
  // { value: "84", label: "Sr.Recruitment Specialist" },
  // { value: "85", label: "Sr.SEO Professional" },
  // { value: "87", label: "Technical Leader" },
  // { value: "88", label: "Trainee Business Development Associate" },
  // { value: "89", label: "Trainee Mobile App Designer" },
  // { value: "90", label: "Trainee QA Engineer" },
  // { value: "100", label: "Trainee Web Designer" },
  // { value: "101", label: "Vice President Marketing" },
  // { value: "102", label: "VP Finance & Administration" },
  // { value: "103", label: "Web Design Team Leader" },
  // { value: "104", label: "Web Designer" },
  // { value: "105", label: "Website Administrator" },
];

export const optionsTechnology = [
  { value: "0", label: "Select Technology" },
  { value: "1", label: "React" },
  { value: "2", label: "Next" },
  { value: "3", label: "React Native" },
  { value: "5", label: "Design" },
  { value: "9", label: "HR" },
  { value: "16", label: "Other" },

  // { value: "4", label: "ASP.NET" },
  // { value: "6", label: "Digital Marketing" },
  // { value: "7", label: "Finance" },
  // { value: "8", label: "Game" },
  // { value: "10", label: "JAVA" },
  // { value: "11", label: "Management" },
  // { value: "12", label: "Marketing" },
  // { value: "13", label: "Mobile" },
  // { value: "14", label: "Mobile QA" },
  // { value: "15", label: "NA" },
  // { value: "17", label: "PHP" },
  // { value: "18", label: "Python" },
  // { value: "19", label: "QA" },
  // { value: "20", label: "R&D" },
  // { value: "21", label: "ROR" },
  // { value: "22", label: "Support" },
  // { value: "23", label: "UrbanIndia" },
  // { value: "24", label: "Web QA" },
];

export const optionsType = [
  { value: "0", label: "Half Day (morning to afternoon)" },
  { value: "1", label: "Half Day (afternoon to evening)" },
  { value: "2", label: "Full Day" },
];

export const optionsReason = [
  { value: "1", label: "Sick Leave" },
  { value: "2", label: "Out of Station" },
  { value: "3", label: "Family Function" },
  { value: "4", label: "Exams" },
  {
    value: "5",
    label: "Attend Marriage/engagement/or any related functions",
  },
  { value: "6", label: "Hourly leaves" },
  { value: "7", label: "Out for work" },
  { value: "8", label: "submission of Project reports" },
  { value: "9", label: "Own Marriage" },
  { value: "10", label: "Religious Function" },
  { value: "11", label: "His/Her Engagement" },
  { value: "12", label: "Project Presentations" },
  { value: "13", label: "Family Issue." },
  { value: "14", label: "Other" },
  { value: "15", label: "Urgent Leave" },
  { value: "16", label: "College Convocation" },
  { value: "17", label: "Getting Engaged" },
  { value: "18", label: "Project Documentation Leave" },
  { value: "19", label: "Submission of Final Project." },
  { value: "20", label: "Presentation Preparation" },
  { value: "21", label: "Festival leave" },
  { value: "22", label: "College Functions" },
  { value: "23", label: "Social Function" },
  { value: "24", label: "Project work - College Visit" },
  { value: "25", label: "Doctor's appointment" },
  { value: "26", label: "Going out with Family" },
  { value: "27", label: "Heavy Rain" },
  { value: "28", label: "Personal Reason" },
  { value: "29", label: "Religious Trip" },
  { value: "30", label: "College Reporting" },
  { value: "31", label: "College Work" },
  { value: "32", label: "Medical Treatment" },
  { value: "33", label: "Marriage Shopping" },
  { value: "34", label: "Matrimonial" },
  { value: "35", label: "Funeral" },
  { value: "36", label: "Rainy Day" },
];
